import './globals.scss';
import Background from '@/components/Background/Background';
import Header from '@/components/Header/Header';
import localFont from 'next/font/local';
import Footer from '@/components/Footer/Footer';
import PageWrapper from '@/components/PageWrapper/PageWrapper';
import { TransitionProvider } from './context/TransitionContext';

export const metadata = {
  title: 'Jim Wilmot',
  description: 'Generated by create next app',
};

const delightFont = localFont({
  src: [
    {
      path: './fonts/Delight/Delight-Black.woff2',
      weight: '900',
      style: 'normal',
    },
    {
      path: './fonts/Delight/Delight-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: './fonts/Delight/Delight-ExtraBold.woff2',
      weight: '800',
      style: 'normal',
    },
    {
      path: './fonts/Delight/Delight-ExtraLight.woff2',
      weight: '200',
      style: 'normal',
    },
    {
      path: './fonts/Delight/Delight-Light.woff2',
      weight: '300',
      style: 'normal',
    },
    {
      path: './fonts/Delight/Delight-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/Delight/Delight-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/Delight/Delight-SemiBold.woff2',
      weight: '600',
      style: 'normal',
    },
    {
      path: './fonts/Delight/Delight-Thin.woff2',
      weight: '100',
      style: 'normal',
    },
  ],
  variable: '--font-delight', // Optional CSS variable
  display: 'swap', // Optional font display strategy
});

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${delightFont.className} `}>
        <TransitionProvider>
          <PageWrapper>
            <Header />
            {children}
            <Footer />
            <Background />
          </PageWrapper>
        </TransitionProvider>
      </body>
    </html>
  );
}
